### ISSUE TITLE
Version 3.5.1 `KeyError: 'script_name'` happen on deploy

### ISSUE THREAD

**Issue by shoichi1023** [Snowflake-Labs/schemachange#152]
when I deploy or dry run migrate, that error is always happend. 

```sh
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/schemachange", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/schemachange/cli.py", line 865, in main
    deploy_command(config) 
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/schemachange/cli.py", line 544, in deploy_command
    print(_log_skip_r.format(script=script))
KeyError: 'script_name'
```

maybe this error happend here.
https://github.com/Snowflake-Labs/schemachange/blob/master/schemachange/cli.py#L240-L258

we use public key authentication.

please check it.

**Comment by CermitDFrog** [comment]
@shoichi1023 This is the same error that I reported in [Issue 151](151). I offered the solution there and it's part of my PR as well.

You should be able to dodge the issue by turning off Verbose logging in the meantime.

**Comment by shoichi1023** [comment]
@CermitDFrog  oh...! I couldn't look up that issue & PR.
thx for your contribute. I'm looking forward to waiting for merge.
